FROM postgres:9.6-alpine
COPY ./sql_ddl/init_db.sql /docker-entrypoint-initdb.d/
COPY ./sql_ddl/schema.sql /docker-entrypoint-initdb.d/

#
# Build stage
#
FROM maven:3.6-jdk-8-slim AS build
COPY src /build/src
COPY pom.xml /build/
RUN mvn -f /build/pom.xml clean package -DskipTests

#
# Package stage
#
FROM openjdk:8-alpine
COPY --from=build /build/target/trading-1.0-SNAPSHOT.jar /usr/local/app/trading/lib/trading_app.jar
ENTRYPOINT ["java","-jar","/usr/local/app/trading/lib/trading_app.jar"]